### ISSUE TITLE
Support mkosi files

### ISSUE THREAD

**Issue by septatrix** [hangxingliu/vscode-systemd#54]
[mkosi](https://github.com/systemd/mkosi) is a systemd project to build OS images which can be used for containers or raw disk images. It uses the same ini-like configuration format which systemd already uses.

Do you think adding support for mkosi configs would be in scope of this project given that is also supports other things like podman/quadlet units?

**Comment by hangxingliu** [comment]
yep i noticed it before while building systemd from their source. it will be added into the extension. but I don't have enough time on this project in recent weeks.

**Comment by hangxingliu** [comment]
<https://github.com/systemd/mkosi/blob/main/mkosi/resources/mkosi.md#configuration-settings>

**Comment by hangxingliu** [comment]
The support for mkosi config files has been added into the main branch:   
https://github.com/hangxingliu/vscode-systemd/compare/38918efbee808ff4c4765c337bf049da064aa348...f68b1ff9aaa5ab8381082ae2b75d85a7f8faa259

You can wait for the next release around June this year. Or you can install the WIP version by installing the artifact from the Github Action pages.
